name: Build and Deploy to GitHub Pages

on:
  push:
    paths:
      - 'config.json'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate static site
        run: node build.js

      - name: Copy static assets (optional)
        run: |
          mkdir -p build/static
          cp -R static/* build/ || true

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          path: build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

      #- name: Notify frontend
      #  run: |
      #    curl -X POST ${{ secrets.WEBHOOK_URL }} \
      #      -H "Content-Type: application/json" \
      #      -d '{"status":"deployed"}'
